// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    Hello: typeof import('./components/Hello.vue')['default']
  }
}

export { }
